baseURL: 'https://kodesiana.com/'
title: "Fahmi Noor Fiqri"
theme: fuji

languageCode: id
defaultContentLanguage: id
hasCJKLanguage: false
enableEmoji: true
enableRobotsTXT: true
summaryLength: 100
paginate: 5

googleAnalytics: "G-WCSBJTCX6E"

taxonomies:
  tag: tags
disableKinds:
  - taxonomy

ignoreErrors:
  - error-disable-taxonomy

outputFormats:
  SearchIndex:
    isPlainText: true
    notAlternative: true
    mediaType: application/json
    path: /search/

outputs:
  home:
    - HTML
    - RSS
    - SearchIndex

permalinks:
  post: '/:section/:filename/'

params:
  author: "Fahmi Noor Fiqri"
  subTitle: "#NgodingItuMudah"
  description: A passionate software engineer and machine learning enthusiast.
  sourceURL: 'https://github.com/fahminlb33/blog-source'

  showWordCounter: true
  showReadTime: true
  showLicenseInFooter: true
  showLicense: true
  showToc: true

  # Open Graph
  og: "/img/logo.png"

  # External Apps
  googleAdsense: "6850104426944295"
  disqusShortname: "kodesiana"

  images:
    - img/og.png

  mainSections:
    - post

  copyrightStartYear: '2018'
  license: CC BY 4.0
  licenseLink: 'http://creativecommons.org/licenses/by/4.0/'
  lazyPlaceholder: /assets/lazyload/dsrca_loading_480x270.svg
  lazyPlaceholderRow: /assets/lazyload/dsrca_loading_960x270.svg
  lazyPlaceholderCol: /assets/lazyload/dsrca_loading_480x540.svg

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: false
  tableOfContents:
    startLevel: 2
    endLevel: 3

menu:
  nav:
    - name: Beranda
      url: /
    - name: Pencarian
      url: /search/
    - name: Repositori
      url: /repositori/
    - name: KFlearning
      url: /kflearning/
    - name: Tentang
      url: /about/
    - name: Arsip
      url: /archives/
    - name: Kebiajakan Privasi
      url: /privacy-policy/
    - name: RSS
      url: /index.xml

  link:
    - name: GitHub
      url: 'https://github.com/fahminlb33'
    - name: Instagram
      url: 'https://instagram.com/fahminoorfiqri'
    - name: Twitter
      url: 'https://twitter.com/fahminoorfiqri'
    - name: LinkedIn
      url: 'https://www.linkedin.com/in/fahmi-noor-fiqri'
