baseURL: 'https://example.com'
title: "Fahmi Noor Fiqri🐈"
theme: fuji

languageCode: id
defaultContentLanguage: id
hasCJKLanguage: false
enableEmoji: true
enableRobotsTXT: true
summaryLength: 100
paginate: 10

taxonomies:
  tag: tags
disableKinds:
  - taxonomy

ignoreErrors:
  - error-disable-taxonomy

outputFormats:
  SearchIndex:
    isPlainText: true
    notAlternative: true
    mediaType: application/json
    path: /search/

outputs:
  home:
    - HTML
    - RSS
    - SearchIndex

permalinks:
  post: '/:section/:filename/'

params:
  author: "Fahmi Noor Fiqri"
  subTitle: "#NgodingItuMudah - A passionate software engineer and machine learning enthusiast."
  description: A passionate software engineer and machine learning enthusiast.
  sourceURL: 'https://github.com/fahminlb33/kodesiana-blog'

  showWordCounter: true
  showReadTime: false
  showLicenseInFooter: false
  showLicense: true
  showToc: true  

  images:
    - img/og.png

  mainSections:
    - post

  copyrightStartYear: '2018'
  license: CC BY 4.0
  licenseLink: 'http://creativecommons.org/licenses/by/4.0/'
  lazyPlaceholder: /assets/lazyload/dsrca_loading_480x270.svg
  lazyPlaceholderRow: /assets/lazyload/dsrca_loading_960x270.svg
  lazyPlaceholderCol: /assets/lazyload/dsrca_loading_480x540.svg

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: false
  tableOfContents:
    startLevel: 2
    endLevel: 3

menu:
  nav:
    - name: Beranda
      url: /
      weight: 1
    - name: Pencarian
      url: /search/
      weight: 2
    - name: Tentang
      url: /about/
      weight: 3
    - name: Arsip
      url: /archives/
      weight: 4
    - name: Kebiajakan Privasi
      url: /privacy-policy/
      weight: 5
    - name: RSS
      url: /index.xml
      weight: 6

  link:
    - name: GitHub
      url: 'https://github.com/fahminlb33'
      weight: 1
    - name: Instagram
      url: 'https://instagram.com/fahminoorfiqri'
      weight: 2
    - name: Twitter
      url: 'https://twitter.com/fahminoorfiqri'
      weight: 3
    - name: LinkedIn
      url: 'https://www.linkedin.com/in/fahmi-noor-fiqri'
      weight: 4
